/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 80
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 46
#define ALIAS_COUNT 0
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_user_header = 1,
  sym_agent_header = 2,
  sym_plan_header = 3,
  sym_review_header = 4,
  anon_sym_SPACE = 5,
  sym_command_marker = 6,
  sym_tool_marker = 7,
  sym_exploration_marker = 8,
  aux_sym_command_subject_token1 = 9,
  sym_action_pipe = 10,
  sym_action_branch = 11,
  sym_action_indent = 12,
  sym_fence_delimiter = 13,
  sym_language = 14,
  sym_fence_padding = 15,
  aux_sym_code_line_token1 = 16,
  aux_sym_code_line_token2 = 17,
  sym_text = 18,
  sym__newline = 19,
  sym_document = 20,
  sym_blank_line = 21,
  sym_command_action = 22,
  sym_tool_action = 23,
  sym_exploration_action = 24,
  sym_command_subject = 25,
  sym_tool_subject = 26,
  sym_command_continuation = 27,
  sym_action_result = 28,
  sym_action_result_continuation = 29,
  sym_exploration_result = 30,
  sym_exploration_continuation = 31,
  sym_command_detail = 32,
  sym_result_text = 33,
  sym_exploration_detail = 34,
  sym_fenced_code_block = 35,
  sym_fence_start = 36,
  sym_fence_end = 37,
  sym_code_fence_content = 38,
  sym_code_line = 39,
  sym_text_line = 40,
  aux_sym_document_repeat1 = 41,
  aux_sym_command_action_repeat1 = 42,
  aux_sym_tool_action_repeat1 = 43,
  aux_sym_exploration_action_repeat1 = 44,
  aux_sym_code_fence_content_repeat1 = 45,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_user_header] = "user_header",
  [sym_agent_header] = "agent_header",
  [sym_plan_header] = "plan_header",
  [sym_review_header] = "review_header",
  [anon_sym_SPACE] = " ",
  [sym_command_marker] = "command_marker",
  [sym_tool_marker] = "tool_marker",
  [sym_exploration_marker] = "exploration_marker",
  [aux_sym_command_subject_token1] = "command_subject_token1",
  [sym_action_pipe] = "action_pipe",
  [sym_action_branch] = "action_branch",
  [sym_action_indent] = "action_indent",
  [sym_fence_delimiter] = "fence_delimiter",
  [sym_language] = "language",
  [sym_fence_padding] = "fence_padding",
  [aux_sym_code_line_token1] = "code_line_token1",
  [aux_sym_code_line_token2] = "code_line_token2",
  [sym_text] = "text",
  [sym__newline] = "_newline",
  [sym_document] = "document",
  [sym_blank_line] = "blank_line",
  [sym_command_action] = "command_action",
  [sym_tool_action] = "tool_action",
  [sym_exploration_action] = "exploration_action",
  [sym_command_subject] = "command_subject",
  [sym_tool_subject] = "tool_subject",
  [sym_command_continuation] = "command_continuation",
  [sym_action_result] = "action_result",
  [sym_action_result_continuation] = "action_result_continuation",
  [sym_exploration_result] = "exploration_result",
  [sym_exploration_continuation] = "exploration_continuation",
  [sym_command_detail] = "command_detail",
  [sym_result_text] = "result_text",
  [sym_exploration_detail] = "exploration_detail",
  [sym_fenced_code_block] = "fenced_code_block",
  [sym_fence_start] = "fence_start",
  [sym_fence_end] = "fence_end",
  [sym_code_fence_content] = "code_fence_content",
  [sym_code_line] = "code_line",
  [sym_text_line] = "text_line",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_command_action_repeat1] = "command_action_repeat1",
  [aux_sym_tool_action_repeat1] = "tool_action_repeat1",
  [aux_sym_exploration_action_repeat1] = "exploration_action_repeat1",
  [aux_sym_code_fence_content_repeat1] = "code_fence_content_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_user_header] = sym_user_header,
  [sym_agent_header] = sym_agent_header,
  [sym_plan_header] = sym_plan_header,
  [sym_review_header] = sym_review_header,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [sym_command_marker] = sym_command_marker,
  [sym_tool_marker] = sym_tool_marker,
  [sym_exploration_marker] = sym_exploration_marker,
  [aux_sym_command_subject_token1] = aux_sym_command_subject_token1,
  [sym_action_pipe] = sym_action_pipe,
  [sym_action_branch] = sym_action_branch,
  [sym_action_indent] = sym_action_indent,
  [sym_fence_delimiter] = sym_fence_delimiter,
  [sym_language] = sym_language,
  [sym_fence_padding] = sym_fence_padding,
  [aux_sym_code_line_token1] = aux_sym_code_line_token1,
  [aux_sym_code_line_token2] = aux_sym_code_line_token2,
  [sym_text] = sym_text,
  [sym__newline] = sym__newline,
  [sym_document] = sym_document,
  [sym_blank_line] = sym_blank_line,
  [sym_command_action] = sym_command_action,
  [sym_tool_action] = sym_tool_action,
  [sym_exploration_action] = sym_exploration_action,
  [sym_command_subject] = sym_command_subject,
  [sym_tool_subject] = sym_tool_subject,
  [sym_command_continuation] = sym_command_continuation,
  [sym_action_result] = sym_action_result,
  [sym_action_result_continuation] = sym_action_result_continuation,
  [sym_exploration_result] = sym_exploration_result,
  [sym_exploration_continuation] = sym_exploration_continuation,
  [sym_command_detail] = sym_command_detail,
  [sym_result_text] = sym_result_text,
  [sym_exploration_detail] = sym_exploration_detail,
  [sym_fenced_code_block] = sym_fenced_code_block,
  [sym_fence_start] = sym_fence_start,
  [sym_fence_end] = sym_fence_end,
  [sym_code_fence_content] = sym_code_fence_content,
  [sym_code_line] = sym_code_line,
  [sym_text_line] = sym_text_line,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_command_action_repeat1] = aux_sym_command_action_repeat1,
  [aux_sym_tool_action_repeat1] = aux_sym_tool_action_repeat1,
  [aux_sym_exploration_action_repeat1] = aux_sym_exploration_action_repeat1,
  [aux_sym_code_fence_content_repeat1] = aux_sym_code_fence_content_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_user_header] = {
    .visible = true,
    .named = true,
  },
  [sym_agent_header] = {
    .visible = true,
    .named = true,
  },
  [sym_plan_header] = {
    .visible = true,
    .named = true,
  },
  [sym_review_header] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [sym_command_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_exploration_marker] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_command_subject_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_action_pipe] = {
    .visible = true,
    .named = true,
  },
  [sym_action_branch] = {
    .visible = true,
    .named = true,
  },
  [sym_action_indent] = {
    .visible = true,
    .named = true,
  },
  [sym_fence_delimiter] = {
    .visible = true,
    .named = true,
  },
  [sym_language] = {
    .visible = true,
    .named = true,
  },
  [sym_fence_padding] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_code_line_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_code_line_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_blank_line] = {
    .visible = true,
    .named = true,
  },
  [sym_command_action] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_action] = {
    .visible = true,
    .named = true,
  },
  [sym_exploration_action] = {
    .visible = true,
    .named = true,
  },
  [sym_command_subject] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_subject] = {
    .visible = true,
    .named = true,
  },
  [sym_command_continuation] = {
    .visible = true,
    .named = true,
  },
  [sym_action_result] = {
    .visible = true,
    .named = true,
  },
  [sym_action_result_continuation] = {
    .visible = true,
    .named = true,
  },
  [sym_exploration_result] = {
    .visible = true,
    .named = true,
  },
  [sym_exploration_continuation] = {
    .visible = true,
    .named = true,
  },
  [sym_command_detail] = {
    .visible = true,
    .named = true,
  },
  [sym_result_text] = {
    .visible = true,
    .named = true,
  },
  [sym_exploration_detail] = {
    .visible = true,
    .named = true,
  },
  [sym_fenced_code_block] = {
    .visible = true,
    .named = true,
  },
  [sym_fence_start] = {
    .visible = true,
    .named = true,
  },
  [sym_fence_end] = {
    .visible = true,
    .named = true,
  },
  [sym_code_fence_content] = {
    .visible = true,
    .named = true,
  },
  [sym_code_line] = {
    .visible = true,
    .named = true,
  },
  [sym_text_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_command_action_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tool_action_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_exploration_action_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_code_fence_content_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_content = 1,
  field_delimiter = 2,
  field_language = 3,
  field_state = 4,
  field_subject = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_content] = "content",
  [field_delimiter] = "delimiter",
  [field_language] = "language",
  [field_state] = "state",
  [field_subject] = "subject",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_state, 0},
  [1] =
    {field_delimiter, 0},
  [2] =
    {field_delimiter, 0},
    {field_language, 1},
  [4] =
    {field_state, 0},
    {field_subject, 2},
  [6] =
    {field_content, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 18,
  [28] = 19,
  [29] = 20,
  [30] = 22,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 40,
  [52] = 50,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 64,
  [79] = 66,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(14);
      if (lookahead == '\n') ADVANCE(130);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(55);
      if (lookahead == '`') ADVANCE(27);
      if (lookahead == 0x2022) ADVANCE(23);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(130);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(130);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(19);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(130);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(61);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(130);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(15);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == '\n') ADVANCE(16);
      END_STATE();
    case 8:
      if (lookahead == '\n') ADVANCE(18);
      END_STATE();
    case 9:
      if (lookahead == '\n') ADVANCE(62);
      END_STATE();
    case 10:
      if (lookahead == '\n') ADVANCE(62);
      if (lookahead == '\r') ADVANCE(9);
      if (lookahead == '`') ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(65);
      END_STATE();
    case 11:
      if (eof) ADVANCE(14);
      if (lookahead == '\n') ADVANCE(130);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(75);
      if (lookahead == '`') ADVANCE(87);
      if (lookahead == 0x2022) ADVANCE(70);
      if (lookahead == '#' ||
          lookahead == 0xf03a) ADVANCE(71);
      if (lookahead == 'A' ||
          lookahead == 0xf06a9) ADVANCE(72);
      if (lookahead == 'U' ||
          lookahead == 0xf007) ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 12:
      if (eof) ADVANCE(14);
      if (lookahead == '\n') ADVANCE(130);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(79);
      if (lookahead == '`') ADVANCE(87);
      if (lookahead == 0x2022) ADVANCE(70);
      if (lookahead == '#' ||
          lookahead == 0xf03a) ADVANCE(71);
      if (lookahead == 'A' ||
          lookahead == 0xf06a9) ADVANCE(72);
      if (lookahead == 'U' ||
          lookahead == 0xf007) ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 13:
      if (eof) ADVANCE(14);
      if (lookahead == '\n') ADVANCE(130);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '`') ADVANCE(87);
      if (lookahead == 0x2022) ADVANCE(70);
      if (lookahead == '#' ||
          lookahead == 0xf03a) ADVANCE(71);
      if (lookahead == 'A' ||
          lookahead == 0xf06a9) ADVANCE(72);
      if (lookahead == 'U' ||
          lookahead == 0xf007) ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_user_header);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_agent_header);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_plan_header);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_review_header);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_SPACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_command_marker);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_tool_marker);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_exploration_marker);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_command_subject_token1);
      if (lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_command_subject_token1);
      if (lookahead == ' ') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_command_subject_token1);
      if (lookahead == 'C') ADVANCE(28);
      if (lookahead == 'E') ADVANCE(54);
      if (lookahead == 'R') ADVANCE(29);
      if (lookahead == 'Y') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_command_subject_token1);
      if (lookahead == '`') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_command_subject_token1);
      if (lookahead == '`') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_command_subject_token1);
      if (lookahead == 'a') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_command_subject_token1);
      if (lookahead == 'a') ADVANCE(42);
      if (lookahead == 'u') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_command_subject_token1);
      if (lookahead == 'a') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_command_subject_token1);
      if (lookahead == 'd') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_command_subject_token1);
      if (lookahead == 'd') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_command_subject_token1);
      if (lookahead == 'e') ADVANCE(31);
      if (lookahead == 'i') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_command_subject_token1);
      if (lookahead == 'e') ADVANCE(32);
      if (lookahead == 'i') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_command_subject_token1);
      if (lookahead == 'g') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_command_subject_token1);
      if (lookahead == 'g') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_command_subject_token1);
      if (lookahead == 'g') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_command_subject_token1);
      if (lookahead == 'i') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_command_subject_token1);
      if (lookahead == 'l') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_command_subject_token1);
      if (lookahead == 'l') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_command_subject_token1);
      if (lookahead == 'l') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_command_subject_token1);
      if (lookahead == 'n') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_command_subject_token1);
      if (lookahead == 'n') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_command_subject_token1);
      if (lookahead == 'n') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_command_subject_token1);
      if (lookahead == 'n') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_command_subject_token1);
      if (lookahead == 'n') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_command_subject_token1);
      if (lookahead == 'n') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_command_subject_token1);
      if (lookahead == 'o') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_command_subject_token1);
      if (lookahead == 'o') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_command_subject_token1);
      if (lookahead == 'p') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_command_subject_token1);
      if (lookahead == 'r') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_command_subject_token1);
      if (lookahead == 'r') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_command_subject_token1);
      if (lookahead == 'u') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_command_subject_token1);
      if (lookahead == 'x') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_command_subject_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_action_pipe);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_action_branch);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_action_indent);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_fence_delimiter);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_language);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_fence_padding);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_code_line_token1);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_code_line_token2);
      if (lookahead == '\n') ADVANCE(62);
      if (lookahead == '\r') ADVANCE(9);
      if (lookahead == '`') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(65);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_code_line_token2);
      if (lookahead == '\n') ADVANCE(62);
      if (lookahead == '\r') ADVANCE(9);
      if (lookahead == '`') ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(65);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_code_line_token2);
      if (lookahead == '\n') ADVANCE(62);
      if (lookahead == '\r') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(65);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '\r') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(17);
      if (lookahead == '\r') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(18);
      if (lookahead == '\r') ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(69);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ' ') ADVANCE(82);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ' ') ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ' ') ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ' ') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ' ') ADVANCE(121);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ' ') ADVANCE(80);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ' ') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ' ') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ' ') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ' ') ADVANCE(81);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ' ') ADVANCE(76);
      if (lookahead == 0x2502) ADVANCE(77);
      if (lookahead == 0x2514) ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ' ') ADVANCE(76);
      if (lookahead == 0x2514) ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'C') ADVANCE(90);
      if (lookahead == 'E') ADVANCE(127);
      if (lookahead == 'R') ADVANCE(88);
      if (lookahead == 'Y') ADVANCE(116);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'C') ADVANCE(117);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'P') ADVANCE(106);
      if (lookahead == 'R') ADVANCE(95);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'Y') ADVANCE(118);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '`') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '`') ADVANCE(86);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'a') ADVANCE(109);
      if (lookahead == 'u') ADVANCE(114);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'a') ADVANCE(109);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'a') ADVANCE(108);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'a') ADVANCE(112);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'd') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'd') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'd') ADVANCE(97);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'e') ADVANCE(125);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'e') ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'e') ADVANCE(128);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'e') ADVANCE(92);
      if (lookahead == 'i') ADVANCE(110);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'e') ADVANCE(93);
      if (lookahead == 'i') ADVANCE(115);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'g') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'g') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'g') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'i') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'i') ADVANCE(113);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'l') ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'l') ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'l') ADVANCE(119);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'l') ADVANCE(105);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'n') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'n') ADVANCE(101);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'n') ADVANCE(104);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'n') ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'n') ADVANCE(100);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'n') ADVANCE(111);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'n') ADVANCE(102);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'o') ADVANCE(124);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'o') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'o') ADVANCE(123);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'o') ADVANCE(122);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'p') ADVANCE(107);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'r') ADVANCE(89);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'r') ADVANCE(99);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'u') ADVANCE(66);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'u') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'v') ADVANCE(103);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'w') ADVANCE(69);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'x') ADVANCE(120);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'x') ADVANCE(68);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 13},
  [2] = {.lex_state = 13},
  [3] = {.lex_state = 13},
  [4] = {.lex_state = 11},
  [5] = {.lex_state = 11},
  [6] = {.lex_state = 11},
  [7] = {.lex_state = 11},
  [8] = {.lex_state = 11},
  [9] = {.lex_state = 12},
  [10] = {.lex_state = 12},
  [11] = {.lex_state = 12},
  [12] = {.lex_state = 12},
  [13] = {.lex_state = 12},
  [14] = {.lex_state = 12},
  [15] = {.lex_state = 12},
  [16] = {.lex_state = 12},
  [17] = {.lex_state = 11},
  [18] = {.lex_state = 11},
  [19] = {.lex_state = 11},
  [20] = {.lex_state = 11},
  [21] = {.lex_state = 11},
  [22] = {.lex_state = 11},
  [23] = {.lex_state = 12},
  [24] = {.lex_state = 12},
  [25] = {.lex_state = 12},
  [26] = {.lex_state = 12},
  [27] = {.lex_state = 12},
  [28] = {.lex_state = 12},
  [29] = {.lex_state = 12},
  [30] = {.lex_state = 12},
  [31] = {.lex_state = 13},
  [32] = {.lex_state = 13},
  [33] = {.lex_state = 13},
  [34] = {.lex_state = 13},
  [35] = {.lex_state = 13},
  [36] = {.lex_state = 13},
  [37] = {.lex_state = 10},
  [38] = {.lex_state = 10},
  [39] = {.lex_state = 10},
  [40] = {.lex_state = 4},
  [41] = {.lex_state = 10},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 4},
  [44] = {.lex_state = 10},
  [45] = {.lex_state = 4},
  [46] = {.lex_state = 10},
  [47] = {.lex_state = 10},
  [48] = {.lex_state = 4},
  [49] = {.lex_state = 10},
  [50] = {.lex_state = 4},
  [51] = {.lex_state = 4},
  [52] = {.lex_state = 4},
  [53] = {.lex_state = 4},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 4},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 3},
  [58] = {.lex_state = 13},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SPACE] = ACTIONS(1),
    [sym_command_marker] = ACTIONS(1),
    [sym_tool_marker] = ACTIONS(1),
    [sym_exploration_marker] = ACTIONS(1),
    [aux_sym_command_subject_token1] = ACTIONS(1),
    [sym_fence_delimiter] = ACTIONS(1),
    [sym_language] = ACTIONS(1),
    [aux_sym_code_line_token2] = ACTIONS(1),
    [sym_text] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(75),
    [sym_blank_line] = STATE(2),
    [sym_command_action] = STATE(2),
    [sym_tool_action] = STATE(2),
    [sym_exploration_action] = STATE(2),
    [sym_fenced_code_block] = STATE(2),
    [sym_fence_start] = STATE(37),
    [sym_text_line] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_user_header] = ACTIONS(5),
    [sym_agent_header] = ACTIONS(5),
    [sym_plan_header] = ACTIONS(5),
    [sym_review_header] = ACTIONS(5),
    [sym_command_marker] = ACTIONS(7),
    [sym_tool_marker] = ACTIONS(9),
    [sym_exploration_marker] = ACTIONS(11),
    [sym_fence_delimiter] = ACTIONS(13),
    [sym_text] = ACTIONS(15),
    [sym__newline] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(7), 1,
      sym_command_marker,
    ACTIONS(9), 1,
      sym_tool_marker,
    ACTIONS(11), 1,
      sym_exploration_marker,
    ACTIONS(13), 1,
      sym_fence_delimiter,
    ACTIONS(15), 1,
      sym_text,
    ACTIONS(17), 1,
      sym__newline,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    STATE(37), 1,
      sym_fence_start,
    ACTIONS(21), 4,
      sym_user_header,
      sym_agent_header,
      sym_plan_header,
      sym_review_header,
    STATE(3), 7,
      sym_blank_line,
      sym_command_action,
      sym_tool_action,
      sym_exploration_action,
      sym_fenced_code_block,
      sym_text_line,
      aux_sym_document_repeat1,
  [40] = 10,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(28), 1,
      sym_command_marker,
    ACTIONS(31), 1,
      sym_tool_marker,
    ACTIONS(34), 1,
      sym_exploration_marker,
    ACTIONS(37), 1,
      sym_fence_delimiter,
    ACTIONS(40), 1,
      sym_text,
    ACTIONS(43), 1,
      sym__newline,
    STATE(37), 1,
      sym_fence_start,
    ACTIONS(25), 4,
      sym_user_header,
      sym_agent_header,
      sym_plan_header,
      sym_review_header,
    STATE(3), 7,
      sym_blank_line,
      sym_command_action,
      sym_tool_action,
      sym_exploration_action,
      sym_fenced_code_block,
      sym_text_line,
      aux_sym_document_repeat1,
  [80] = 6,
    ACTIONS(48), 1,
      sym_action_pipe,
    ACTIONS(50), 1,
      sym_action_branch,
    ACTIONS(52), 1,
      sym_action_indent,
    ACTIONS(54), 1,
      sym_text,
    STATE(5), 4,
      sym_command_continuation,
      sym_action_result,
      sym_action_result_continuation,
      aux_sym_command_action_repeat1,
    ACTIONS(46), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_agent_header,
      sym_plan_header,
      sym_review_header,
      sym_command_marker,
      sym_tool_marker,
      sym_exploration_marker,
      sym_fence_delimiter,
      sym__newline,
  [111] = 6,
    ACTIONS(48), 1,
      sym_action_pipe,
    ACTIONS(50), 1,
      sym_action_branch,
    ACTIONS(52), 1,
      sym_action_indent,
    ACTIONS(58), 1,
      sym_text,
    STATE(7), 4,
      sym_command_continuation,
      sym_action_result,
      sym_action_result_continuation,
      aux_sym_command_action_repeat1,
    ACTIONS(56), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_agent_header,
      sym_plan_header,
      sym_review_header,
      sym_command_marker,
      sym_tool_marker,
      sym_exploration_marker,
      sym_fence_delimiter,
      sym__newline,
  [142] = 6,
    ACTIONS(48), 1,
      sym_action_pipe,
    ACTIONS(50), 1,
      sym_action_branch,
    ACTIONS(52), 1,
      sym_action_indent,
    ACTIONS(62), 1,
      sym_text,
    STATE(8), 4,
      sym_command_continuation,
      sym_action_result,
      sym_action_result_continuation,
      aux_sym_command_action_repeat1,
    ACTIONS(60), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_agent_header,
      sym_plan_header,
      sym_review_header,
      sym_command_marker,
      sym_tool_marker,
      sym_exploration_marker,
      sym_fence_delimiter,
      sym__newline,
  [173] = 6,
    ACTIONS(66), 1,
      sym_action_pipe,
    ACTIONS(69), 1,
      sym_action_branch,
    ACTIONS(72), 1,
      sym_action_indent,
    ACTIONS(75), 1,
      sym_text,
    STATE(7), 4,
      sym_command_continuation,
      sym_action_result,
      sym_action_result_continuation,
      aux_sym_command_action_repeat1,
    ACTIONS(64), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_agent_header,
      sym_plan_header,
      sym_review_header,
      sym_command_marker,
      sym_tool_marker,
      sym_exploration_marker,
      sym_fence_delimiter,
      sym__newline,
  [204] = 6,
    ACTIONS(48), 1,
      sym_action_pipe,
    ACTIONS(50), 1,
      sym_action_branch,
    ACTIONS(52), 1,
      sym_action_indent,
    ACTIONS(79), 1,
      sym_text,
    STATE(7), 4,
      sym_command_continuation,
      sym_action_result,
      sym_action_result_continuation,
      aux_sym_command_action_repeat1,
    ACTIONS(77), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_agent_header,
      sym_plan_header,
      sym_review_header,
      sym_command_marker,
      sym_tool_marker,
      sym_exploration_marker,
      sym_fence_delimiter,
      sym__newline,
  [235] = 5,
    ACTIONS(83), 1,
      sym_action_branch,
    ACTIONS(85), 1,
      sym_action_indent,
    ACTIONS(87), 1,
      sym_text,
    STATE(11), 3,
      sym_exploration_result,
      sym_exploration_continuation,
      aux_sym_exploration_action_repeat1,
    ACTIONS(81), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_agent_header,
      sym_plan_header,
      sym_review_header,
      sym_command_marker,
      sym_tool_marker,
      sym_exploration_marker,
      sym_fence_delimiter,
      sym__newline,
  [262] = 5,
    ACTIONS(91), 1,
      sym_action_branch,
    ACTIONS(93), 1,
      sym_action_indent,
    ACTIONS(95), 1,
      sym_text,
    STATE(12), 3,
      sym_action_result,
      sym_action_result_continuation,
      aux_sym_tool_action_repeat1,
    ACTIONS(89), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_agent_header,
      sym_plan_header,
      sym_review_header,
      sym_command_marker,
      sym_tool_marker,
      sym_exploration_marker,
      sym_fence_delimiter,
      sym__newline,
  [289] = 5,
    ACTIONS(83), 1,
      sym_action_branch,
    ACTIONS(85), 1,
      sym_action_indent,
    ACTIONS(99), 1,
      sym_text,
    STATE(15), 3,
      sym_exploration_result,
      sym_exploration_continuation,
      aux_sym_exploration_action_repeat1,
    ACTIONS(97), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_agent_header,
      sym_plan_header,
      sym_review_header,
      sym_command_marker,
      sym_tool_marker,
      sym_exploration_marker,
      sym_fence_delimiter,
      sym__newline,
  [316] = 5,
    ACTIONS(91), 1,
      sym_action_branch,
    ACTIONS(93), 1,
      sym_action_indent,
    ACTIONS(103), 1,
      sym_text,
    STATE(13), 3,
      sym_action_result,
      sym_action_result_continuation,
      aux_sym_tool_action_repeat1,
    ACTIONS(101), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_agent_header,
      sym_plan_header,
      sym_review_header,
      sym_command_marker,
      sym_tool_marker,
      sym_exploration_marker,
      sym_fence_delimiter,
      sym__newline,
  [343] = 5,
    ACTIONS(107), 1,
      sym_action_branch,
    ACTIONS(110), 1,
      sym_action_indent,
    ACTIONS(113), 1,
      sym_text,
    STATE(13), 3,
      sym_action_result,
      sym_action_result_continuation,
      aux_sym_tool_action_repeat1,
    ACTIONS(105), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_agent_header,
      sym_plan_header,
      sym_review_header,
      sym_command_marker,
      sym_tool_marker,
      sym_exploration_marker,
      sym_fence_delimiter,
      sym__newline,
  [370] = 5,
    ACTIONS(91), 1,
      sym_action_branch,
    ACTIONS(93), 1,
      sym_action_indent,
    ACTIONS(117), 1,
      sym_text,
    STATE(13), 3,
      sym_action_result,
      sym_action_result_continuation,
      aux_sym_tool_action_repeat1,
    ACTIONS(115), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_agent_header,
      sym_plan_header,
      sym_review_header,
      sym_command_marker,
      sym_tool_marker,
      sym_exploration_marker,
      sym_fence_delimiter,
      sym__newline,
  [397] = 5,
    ACTIONS(121), 1,
      sym_action_branch,
    ACTIONS(124), 1,
      sym_action_indent,
    ACTIONS(127), 1,
      sym_text,
    STATE(15), 3,
      sym_exploration_result,
      sym_exploration_continuation,
      aux_sym_exploration_action_repeat1,
    ACTIONS(119), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_agent_header,
      sym_plan_header,
      sym_review_header,
      sym_command_marker,
      sym_tool_marker,
      sym_exploration_marker,
      sym_fence_delimiter,
      sym__newline,
  [424] = 5,
    ACTIONS(91), 1,
      sym_action_branch,
    ACTIONS(93), 1,
      sym_action_indent,
    ACTIONS(131), 1,
      sym_text,
    STATE(14), 3,
      sym_action_result,
      sym_action_result_continuation,
      aux_sym_tool_action_repeat1,
    ACTIONS(129), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_agent_header,
      sym_plan_header,
      sym_review_header,
      sym_command_marker,
      sym_tool_marker,
      sym_exploration_marker,
      sym_fence_delimiter,
      sym__newline,
  [451] = 2,
    ACTIONS(135), 1,
      sym_text,
    ACTIONS(133), 13,
      ts_builtin_sym_end,
      sym_user_header,
      sym_agent_header,
      sym_plan_header,
      sym_review_header,
      sym_command_marker,
      sym_tool_marker,
      sym_exploration_marker,
      sym_action_pipe,
      sym_action_branch,
      sym_action_indent,
      sym_fence_delimiter,
      sym__newline,
  [470] = 2,
    ACTIONS(139), 1,
      sym_text,
    ACTIONS(137), 13,
      ts_builtin_sym_end,
      sym_user_header,
      sym_agent_header,
      sym_plan_header,
      sym_review_header,
      sym_command_marker,
      sym_tool_marker,
      sym_exploration_marker,
      sym_action_pipe,
      sym_action_branch,
      sym_action_indent,
      sym_fence_delimiter,
      sym__newline,
  [489] = 2,
    ACTIONS(143), 1,
      sym_text,
    ACTIONS(141), 13,
      ts_builtin_sym_end,
      sym_user_header,
      sym_agent_header,
      sym_plan_header,
      sym_review_header,
      sym_command_marker,
      sym_tool_marker,
      sym_exploration_marker,
      sym_action_pipe,
      sym_action_branch,
      sym_action_indent,
      sym_fence_delimiter,
      sym__newline,
  [508] = 2,
    ACTIONS(147), 1,
      sym_text,
    ACTIONS(145), 13,
      ts_builtin_sym_end,
      sym_user_header,
      sym_agent_header,
      sym_plan_header,
      sym_review_header,
      sym_command_marker,
      sym_tool_marker,
      sym_exploration_marker,
      sym_action_pipe,
      sym_action_branch,
      sym_action_indent,
      sym_fence_delimiter,
      sym__newline,
  [527] = 2,
    ACTIONS(151), 1,
      sym_text,
    ACTIONS(149), 13,
      ts_builtin_sym_end,
      sym_user_header,
      sym_agent_header,
      sym_plan_header,
      sym_review_header,
      sym_command_marker,
      sym_tool_marker,
      sym_exploration_marker,
      sym_action_pipe,
      sym_action_branch,
      sym_action_indent,
      sym_fence_delimiter,
      sym__newline,
  [546] = 2,
    ACTIONS(155), 1,
      sym_text,
    ACTIONS(153), 13,
      ts_builtin_sym_end,
      sym_user_header,
      sym_agent_header,
      sym_plan_header,
      sym_review_header,
      sym_command_marker,
      sym_tool_marker,
      sym_exploration_marker,
      sym_action_pipe,
      sym_action_branch,
      sym_action_indent,
      sym_fence_delimiter,
      sym__newline,
  [565] = 2,
    ACTIONS(159), 1,
      sym_text,
    ACTIONS(157), 12,
      ts_builtin_sym_end,
      sym_user_header,
      sym_agent_header,
      sym_plan_header,
      sym_review_header,
      sym_command_marker,
      sym_tool_marker,
      sym_exploration_marker,
      sym_action_branch,
      sym_action_indent,
      sym_fence_delimiter,
      sym__newline,
  [583] = 2,
    ACTIONS(163), 1,
      sym_text,
    ACTIONS(161), 12,
      ts_builtin_sym_end,
      sym_user_header,
      sym_agent_header,
      sym_plan_header,
      sym_review_header,
      sym_command_marker,
      sym_tool_marker,
      sym_exploration_marker,
      sym_action_branch,
      sym_action_indent,
      sym_fence_delimiter,
      sym__newline,
  [601] = 2,
    ACTIONS(167), 1,
      sym_text,
    ACTIONS(165), 12,
      ts_builtin_sym_end,
      sym_user_header,
      sym_agent_header,
      sym_plan_header,
      sym_review_header,
      sym_command_marker,
      sym_tool_marker,
      sym_exploration_marker,
      sym_action_branch,
      sym_action_indent,
      sym_fence_delimiter,
      sym__newline,
  [619] = 2,
    ACTIONS(171), 1,
      sym_text,
    ACTIONS(169), 12,
      ts_builtin_sym_end,
      sym_user_header,
      sym_agent_header,
      sym_plan_header,
      sym_review_header,
      sym_command_marker,
      sym_tool_marker,
      sym_exploration_marker,
      sym_action_branch,
      sym_action_indent,
      sym_fence_delimiter,
      sym__newline,
  [637] = 2,
    ACTIONS(139), 1,
      sym_text,
    ACTIONS(137), 12,
      ts_builtin_sym_end,
      sym_user_header,
      sym_agent_header,
      sym_plan_header,
      sym_review_header,
      sym_command_marker,
      sym_tool_marker,
      sym_exploration_marker,
      sym_action_branch,
      sym_action_indent,
      sym_fence_delimiter,
      sym__newline,
  [655] = 2,
    ACTIONS(143), 1,
      sym_text,
    ACTIONS(141), 12,
      ts_builtin_sym_end,
      sym_user_header,
      sym_agent_header,
      sym_plan_header,
      sym_review_header,
      sym_command_marker,
      sym_tool_marker,
      sym_exploration_marker,
      sym_action_branch,
      sym_action_indent,
      sym_fence_delimiter,
      sym__newline,
  [673] = 2,
    ACTIONS(147), 1,
      sym_text,
    ACTIONS(145), 12,
      ts_builtin_sym_end,
      sym_user_header,
      sym_agent_header,
      sym_plan_header,
      sym_review_header,
      sym_command_marker,
      sym_tool_marker,
      sym_exploration_marker,
      sym_action_branch,
      sym_action_indent,
      sym_fence_delimiter,
      sym__newline,
  [691] = 2,
    ACTIONS(155), 1,
      sym_text,
    ACTIONS(153), 12,
      ts_builtin_sym_end,
      sym_user_header,
      sym_agent_header,
      sym_plan_header,
      sym_review_header,
      sym_command_marker,
      sym_tool_marker,
      sym_exploration_marker,
      sym_action_branch,
      sym_action_indent,
      sym_fence_delimiter,
      sym__newline,
  [709] = 2,
    ACTIONS(175), 1,
      sym_text,
    ACTIONS(173), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_agent_header,
      sym_plan_header,
      sym_review_header,
      sym_command_marker,
      sym_tool_marker,
      sym_exploration_marker,
      sym_fence_delimiter,
      sym__newline,
  [725] = 2,
    ACTIONS(179), 1,
      sym_text,
    ACTIONS(177), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_agent_header,
      sym_plan_header,
      sym_review_header,
      sym_command_marker,
      sym_tool_marker,
      sym_exploration_marker,
      sym_fence_delimiter,
      sym__newline,
  [741] = 2,
    ACTIONS(183), 1,
      sym_text,
    ACTIONS(181), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_agent_header,
      sym_plan_header,
      sym_review_header,
      sym_command_marker,
      sym_tool_marker,
      sym_exploration_marker,
      sym_fence_delimiter,
      sym__newline,
  [757] = 2,
    ACTIONS(187), 1,
      sym_text,
    ACTIONS(185), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_agent_header,
      sym_plan_header,
      sym_review_header,
      sym_command_marker,
      sym_tool_marker,
      sym_exploration_marker,
      sym_fence_delimiter,
      sym__newline,
  [773] = 2,
    ACTIONS(191), 1,
      sym_text,
    ACTIONS(189), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_agent_header,
      sym_plan_header,
      sym_review_header,
      sym_command_marker,
      sym_tool_marker,
      sym_exploration_marker,
      sym_fence_delimiter,
      sym__newline,
  [789] = 2,
    ACTIONS(195), 1,
      sym_text,
    ACTIONS(193), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_agent_header,
      sym_plan_header,
      sym_review_header,
      sym_command_marker,
      sym_tool_marker,
      sym_exploration_marker,
      sym_fence_delimiter,
      sym__newline,
  [805] = 5,
    ACTIONS(197), 1,
      sym_fence_delimiter,
    STATE(36), 1,
      sym_fence_end,
    STATE(58), 1,
      sym_code_fence_content,
    ACTIONS(199), 2,
      aux_sym_code_line_token1,
      aux_sym_code_line_token2,
    STATE(39), 2,
      sym_code_line,
      aux_sym_code_fence_content_repeat1,
  [823] = 3,
    ACTIONS(201), 1,
      sym_fence_delimiter,
    ACTIONS(203), 2,
      aux_sym_code_line_token1,
      aux_sym_code_line_token2,
    STATE(38), 2,
      sym_code_line,
      aux_sym_code_fence_content_repeat1,
  [835] = 3,
    ACTIONS(206), 1,
      sym_fence_delimiter,
    ACTIONS(199), 2,
      aux_sym_code_line_token1,
      aux_sym_code_line_token2,
    STATE(38), 2,
      sym_code_line,
      aux_sym_code_fence_content_repeat1,
  [847] = 3,
    ACTIONS(208), 1,
      aux_sym_command_subject_token1,
    ACTIONS(210), 1,
      sym__newline,
    STATE(79), 1,
      sym_result_text,
  [857] = 2,
    ACTIONS(212), 1,
      sym_fence_delimiter,
    ACTIONS(214), 2,
      aux_sym_code_line_token1,
      aux_sym_code_line_token2,
  [865] = 3,
    ACTIONS(216), 1,
      sym_language,
    ACTIONS(218), 1,
      sym_fence_padding,
    ACTIONS(220), 1,
      sym__newline,
  [875] = 3,
    ACTIONS(222), 1,
      aux_sym_command_subject_token1,
    ACTIONS(224), 1,
      sym__newline,
    STATE(77), 1,
      sym_exploration_detail,
  [885] = 2,
    ACTIONS(226), 1,
      sym_fence_delimiter,
    ACTIONS(228), 2,
      aux_sym_code_line_token1,
      aux_sym_code_line_token2,
  [893] = 3,
    ACTIONS(222), 1,
      aux_sym_command_subject_token1,
    ACTIONS(230), 1,
      sym__newline,
    STATE(74), 1,
      sym_exploration_detail,
  [903] = 2,
    ACTIONS(232), 1,
      sym_fence_delimiter,
    ACTIONS(234), 2,
      aux_sym_code_line_token1,
      aux_sym_code_line_token2,
  [911] = 2,
    ACTIONS(236), 1,
      sym_fence_delimiter,
    ACTIONS(238), 2,
      aux_sym_code_line_token1,
      aux_sym_code_line_token2,
  [919] = 3,
    ACTIONS(240), 1,
      aux_sym_command_subject_token1,
    ACTIONS(242), 1,
      sym__newline,
    STATE(76), 1,
      sym_command_detail,
  [929] = 2,
    ACTIONS(244), 1,
      sym_fence_delimiter,
    ACTIONS(246), 2,
      aux_sym_code_line_token1,
      aux_sym_code_line_token2,
  [937] = 3,
    ACTIONS(208), 1,
      aux_sym_command_subject_token1,
    ACTIONS(248), 1,
      sym__newline,
    STATE(64), 1,
      sym_result_text,
  [947] = 3,
    ACTIONS(208), 1,
      aux_sym_command_subject_token1,
    ACTIONS(250), 1,
      sym__newline,
    STATE(66), 1,
      sym_result_text,
  [957] = 3,
    ACTIONS(208), 1,
      aux_sym_command_subject_token1,
    ACTIONS(252), 1,
      sym__newline,
    STATE(78), 1,
      sym_result_text,
  [967] = 2,
    ACTIONS(254), 1,
      aux_sym_command_subject_token1,
    STATE(71), 1,
      sym_command_subject,
  [974] = 2,
    ACTIONS(256), 1,
      anon_sym_SPACE,
    ACTIONS(258), 1,
      sym__newline,
  [981] = 2,
    ACTIONS(260), 1,
      aux_sym_command_subject_token1,
    STATE(61), 1,
      sym_tool_subject,
  [988] = 2,
    ACTIONS(262), 1,
      sym_fence_padding,
    ACTIONS(264), 1,
      sym__newline,
  [995] = 2,
    ACTIONS(266), 1,
      sym_fence_padding,
    ACTIONS(268), 1,
      sym__newline,
  [1002] = 2,
    ACTIONS(197), 1,
      sym_fence_delimiter,
    STATE(32), 1,
      sym_fence_end,
  [1009] = 2,
    ACTIONS(270), 1,
      anon_sym_SPACE,
    ACTIONS(272), 1,
      sym__newline,
  [1016] = 1,
    ACTIONS(274), 1,
      sym__newline,
  [1020] = 1,
    ACTIONS(276), 1,
      sym__newline,
  [1024] = 1,
    ACTIONS(278), 1,
      sym__newline,
  [1028] = 1,
    ACTIONS(280), 1,
      sym__newline,
  [1032] = 1,
    ACTIONS(282), 1,
      sym__newline,
  [1036] = 1,
    ACTIONS(284), 1,
      sym__newline,
  [1040] = 1,
    ACTIONS(286), 1,
      sym__newline,
  [1044] = 1,
    ACTIONS(288), 1,
      sym__newline,
  [1048] = 1,
    ACTIONS(290), 1,
      sym__newline,
  [1052] = 1,
    ACTIONS(292), 1,
      sym__newline,
  [1056] = 1,
    ACTIONS(294), 1,
      sym__newline,
  [1060] = 1,
    ACTIONS(296), 1,
      sym__newline,
  [1064] = 1,
    ACTIONS(298), 1,
      sym__newline,
  [1068] = 1,
    ACTIONS(300), 1,
      sym__newline,
  [1072] = 1,
    ACTIONS(302), 1,
      sym__newline,
  [1076] = 1,
    ACTIONS(304), 1,
      ts_builtin_sym_end,
  [1080] = 1,
    ACTIONS(306), 1,
      sym__newline,
  [1084] = 1,
    ACTIONS(308), 1,
      sym__newline,
  [1088] = 1,
    ACTIONS(310), 1,
      sym__newline,
  [1092] = 1,
    ACTIONS(312), 1,
      sym__newline,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 40,
  [SMALL_STATE(4)] = 80,
  [SMALL_STATE(5)] = 111,
  [SMALL_STATE(6)] = 142,
  [SMALL_STATE(7)] = 173,
  [SMALL_STATE(8)] = 204,
  [SMALL_STATE(9)] = 235,
  [SMALL_STATE(10)] = 262,
  [SMALL_STATE(11)] = 289,
  [SMALL_STATE(12)] = 316,
  [SMALL_STATE(13)] = 343,
  [SMALL_STATE(14)] = 370,
  [SMALL_STATE(15)] = 397,
  [SMALL_STATE(16)] = 424,
  [SMALL_STATE(17)] = 451,
  [SMALL_STATE(18)] = 470,
  [SMALL_STATE(19)] = 489,
  [SMALL_STATE(20)] = 508,
  [SMALL_STATE(21)] = 527,
  [SMALL_STATE(22)] = 546,
  [SMALL_STATE(23)] = 565,
  [SMALL_STATE(24)] = 583,
  [SMALL_STATE(25)] = 601,
  [SMALL_STATE(26)] = 619,
  [SMALL_STATE(27)] = 637,
  [SMALL_STATE(28)] = 655,
  [SMALL_STATE(29)] = 673,
  [SMALL_STATE(30)] = 691,
  [SMALL_STATE(31)] = 709,
  [SMALL_STATE(32)] = 725,
  [SMALL_STATE(33)] = 741,
  [SMALL_STATE(34)] = 757,
  [SMALL_STATE(35)] = 773,
  [SMALL_STATE(36)] = 789,
  [SMALL_STATE(37)] = 805,
  [SMALL_STATE(38)] = 823,
  [SMALL_STATE(39)] = 835,
  [SMALL_STATE(40)] = 847,
  [SMALL_STATE(41)] = 857,
  [SMALL_STATE(42)] = 865,
  [SMALL_STATE(43)] = 875,
  [SMALL_STATE(44)] = 885,
  [SMALL_STATE(45)] = 893,
  [SMALL_STATE(46)] = 903,
  [SMALL_STATE(47)] = 911,
  [SMALL_STATE(48)] = 919,
  [SMALL_STATE(49)] = 929,
  [SMALL_STATE(50)] = 937,
  [SMALL_STATE(51)] = 947,
  [SMALL_STATE(52)] = 957,
  [SMALL_STATE(53)] = 967,
  [SMALL_STATE(54)] = 974,
  [SMALL_STATE(55)] = 981,
  [SMALL_STATE(56)] = 988,
  [SMALL_STATE(57)] = 995,
  [SMALL_STATE(58)] = 1002,
  [SMALL_STATE(59)] = 1009,
  [SMALL_STATE(60)] = 1016,
  [SMALL_STATE(61)] = 1020,
  [SMALL_STATE(62)] = 1024,
  [SMALL_STATE(63)] = 1028,
  [SMALL_STATE(64)] = 1032,
  [SMALL_STATE(65)] = 1036,
  [SMALL_STATE(66)] = 1040,
  [SMALL_STATE(67)] = 1044,
  [SMALL_STATE(68)] = 1048,
  [SMALL_STATE(69)] = 1052,
  [SMALL_STATE(70)] = 1056,
  [SMALL_STATE(71)] = 1060,
  [SMALL_STATE(72)] = 1064,
  [SMALL_STATE(73)] = 1068,
  [SMALL_STATE(74)] = 1072,
  [SMALL_STATE(75)] = 1076,
  [SMALL_STATE(76)] = 1080,
  [SMALL_STATE(77)] = 1084,
  [SMALL_STATE(78)] = 1088,
  [SMALL_STATE(79)] = 1092,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_action, 2, 0, 1),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command_action, 2, 0, 1),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_action, 3, 0, 1),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command_action, 3, 0, 1),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_action, 4, 0, 4),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command_action, 4, 0, 4),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_command_action_repeat1, 2, 0, 0),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_command_action_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_command_action_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_command_action_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_command_action_repeat1, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_action, 5, 0, 4),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command_action, 5, 0, 4),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exploration_action, 2, 0, 1),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_exploration_action, 2, 0, 1),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_action, 2, 0, 1),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tool_action, 2, 0, 1),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exploration_action, 3, 0, 1),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_exploration_action, 3, 0, 1),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_action, 3, 0, 1),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tool_action, 3, 0, 1),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tool_action_repeat1, 2, 0, 0),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tool_action_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tool_action_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tool_action_repeat1, 2, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_action, 5, 0, 4),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tool_action, 5, 0, 4),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_exploration_action_repeat1, 2, 0, 0),
  [121] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_exploration_action_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [124] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_exploration_action_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_exploration_action_repeat1, 2, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_action, 4, 0, 4),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tool_action, 4, 0, 4),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_continuation, 2, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command_continuation, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_action_result, 2, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_action_result, 2, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_action_result_continuation, 2, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_action_result_continuation, 2, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_action_result, 3, 0, 5),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_action_result, 3, 0, 5),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_continuation, 3, 0, 5),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command_continuation, 3, 0, 5),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_action_result_continuation, 3, 0, 5),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_action_result_continuation, 3, 0, 5),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exploration_continuation, 2, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_exploration_continuation, 2, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exploration_result, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_exploration_result, 2, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exploration_result, 3, 0, 5),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_exploration_result, 3, 0, 5),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exploration_continuation, 3, 0, 5),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_exploration_continuation, 3, 0, 5),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_blank_line, 1, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_blank_line, 1, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fenced_code_block, 3, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fenced_code_block, 3, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fence_end, 2, 0, 2),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fence_end, 2, 0, 2),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fence_end, 3, 0, 2),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fence_end, 3, 0, 2),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text_line, 2, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text_line, 2, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fenced_code_block, 2, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fenced_code_block, 2, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_code_fence_content_repeat1, 2, 0, 0),
  [203] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_code_fence_content_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_fence_content, 1, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fence_start, 3, 0, 3),
  [214] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fence_start, 3, 0, 3),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fence_start, 3, 0, 2),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fence_start, 3, 0, 2),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fence_start, 4, 0, 3),
  [234] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fence_start, 4, 0, 3),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_line, 1, 0, 0),
  [238] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_line, 1, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fence_start, 2, 0, 2),
  [246] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fence_start, 2, 0, 2),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_result_text, 1, 0, 0),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_detail, 1, 0, 0),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_subject, 1, 0, 0),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_subject, 1, 0, 0),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [298] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exploration_detail, 1, 0, 0),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [304] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_acp(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
