local M = {
	acp = "󰚩",
	action = "󰌵",
	agent = "󰚩",
	arrow_right = "",
	blink = "󰂫",
	busy = "󰔟",
	call = "󰃷",
	changes = "󰏫",
	close = "󰅖",
	code = "",
	color = "",
	command = "",
	config = "",
	context = "󰉉",
	diagnostics = "󰒡",
	edit = "",
	enter = "󰌑",
	error = "",
	file = "󰈙",
	filter = "",
	fold = "",
	history = "󰋚",
	hint = "󰌶",
	hierarchy = "󰙅",
	help = "󰋖",
	idle = "",
	info = "",
	inspect = "󰍉",
	jump = "󰁔",
	key = "󰌌",
	link = "",
	location = "",
	lsp = "",
	map = "󰍍",
	model = "󰚩",
	note = "󰎚",
	package = "󰏗",
	pulse_empty = "",
	pulse_full = "",
	pulse_mid = "",
	preferred = "",
	prompt = "󰭻",
	quickfix = "󰁨",
	reference = "",
	restore = "󰑓",
	scope = "󰆐",
	search = "",
	section = "",
	send = "󰒊",
	session = "󰒲",
	source = "󰈙",
	status = "󰐊",
	stop = "",
	symbol = "󰆧",
	terminal = "",
	tool = "",
	treesitter = "",
	type = "󰊄",
	user = "",
	warning = "",
	yank = "",
}

function M.title(text, icon)
	return ("%s %s"):format(icon or M.acp, text or "ACP")
end

function M.quickfix_title(text)
	return M.title(text, M.quickfix)
end

return M
